apiVersion: apps/v1
kind: Deployment
metadata:
  name: student-service
  namespace: bits-scalable-services
spec:
  replicas: 1
  selector:
    matchLabels:
      app: student-service
  template:
    metadata:
      labels:
        app: student-service
    spec:
      containers:
      - name: student-service
        image: k8s-student-service
        imagePullPolicy: Never
        ports:
        - containerPort: 4001