apiVersion: v1
kind: Service
metadata:
  name: student-service
  namespace: bits-scalable-services
spec:
  type: NodePort
  selector:
    app: student-service
  ports:
    - port: 4001
      targetPort: 4001
